atlo/atlo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("main/", include("main.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atlo/main/urls.py
from django.urls import path

from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("register/", views.registerPage, name="register"),
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("new_traffic/", views.addNewTraffic, name="add_new_traffic"),
    path("account_page/<str:pk>", views.editAccount, name="account_page"),
    path("delete_traffic/<str:pk>", views.deleteTraffic, name="delete_traffic"),
    path("activate_traffic/<str:pk>", views.activate_traffic, name="activate_traffic"),
]

atlo/main/models.py
from django.db import models
from django.contrib.auth.models import User


class Traffic(models.Model):
    """Number of traffic from each side for user.
    Gets from registration and changed in the main screen
    """

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    from_left = models.IntegerField(default=1, null=True)
    from_right = models.IntegerField(default=1, null=True)
    from_top = models.IntegerField(default=1, null=True)
    from_bottom = models.IntegerField(default=1, null=True)

    def __str__(self):
        return f"from left : {self.from_left}, from right : {self.from_right}, from top : {self.from_top}, from bottom : {self.from_bottom}"

    class Meta:
        verbose_name = "Traffic size"
        verbose_name_plural = "Traffic sizes"


class OtherParam(models.Model):
    """Other parameters of calculations
    speed - Speed of cars.
    iterations - how many cycles will the traffic light work

    Added and changed in the main screen
    """

    traffic = models.OneToOneField(Traffic, on_delete=models.CASCADE)
    speed = models.IntegerField(default=60)
    iterations = models.IntegerField(default=15)

    def __str__(self):
        return f"Speed : {self.speed} km/h; Iterations : {self.iterations}"


class Results(models.Model):
    """Results of calculations - is time of green light in bouth direction for user
    and numbers of collapses in each directions

    time_lf_rt - Time of green light in left-right direction
    time_tp_bm - Time of green light in top-bottom direction
    top_collapse - number when number of cars from top direction > 1.5 * the capacity of the cross
    bottom_collapse - number when number of cars from bottom direction > 1.5 * the capacity of the cross
    left_collapse - number when number of cars from left direction > 1.5 * the capacity of the cross
    right_collapse - number when number of cars from right direction > 1.5 * the capacity of the cross
    created - date of calculation
    """

    traffic = models.OneToOneField(Traffic, on_delete=models.CASCADE)
    time_lf_rt = models.IntegerField()
    time_tp_bm = models.IntegerField()
    top_collapse = models.IntegerField()
    bottom_collapse = models.IntegerField()
    left_collapse = models.IntegerField()
    right_collapse = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Green time from left to right : {self.time_lf_rt}, Green time from top to bottom : {self.time_tp_bm}"


class Profile(models.Model):
    """User's picture"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} Profile"

atlo/main/forms.py
from django.forms import ModelForm, CharField, TextInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Traffic, OtherParam, Profile

ATTRS_INPUT = {
    "class": "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-1.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
}


class CreateUserForm(UserCreationForm):

    username = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    email = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    password1 = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    password2 = CharField(widget=TextInput(attrs=ATTRS_INPUT))

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class TrafficForm(ModelForm):
    from_top = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    from_bottom = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    from_left = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    from_right = CharField(widget=TextInput(attrs=ATTRS_INPUT))

    class Meta:
        model = Traffic
        fields = ["from_top", "from_bottom", "from_left", "from_right"]


class OtherParamForm(ModelForm):
    use_speed = forms.BooleanField(required=False)
    speed = CharField(widget=TextInput(attrs=ATTRS_INPUT))
    use_iterations = forms.BooleanField(required=False)
    iterations = CharField(widget=TextInput(attrs=ATTRS_INPUT))

    class Meta:
        model = OtherParam
        fields = ["speed", "iterations"]


class ImageForm(ModelForm):
    image = CharField(
        widget=TextInput(
            attrs={
                "class": "form-control block w-full px-2 py-1 text-sm font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
                "type": "file",
                "id": "formFile",
            }
        )
    )

    class Meta:
        model = Profile
        fields = ["image"]

atlo/main/views/log_reg_views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db import transaction

from ..forms import CreateUserForm, TrafficForm
from ..models import Profile


@transaction.atomic  # if something wrong - nofing save to DB
def registerPage(request):
    form = CreateUserForm()
    form_traffic = TrafficForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile(user=user, image="default-user-icon-21.jpg")
            profile.save()
            username = form.cleaned_data.get("username")
            messages.success(request, "Account was created for " + username)
            login(request, user)
            return redirect("main:add_new_traffic")
    context = {"form": form}
    return render(request, "main/register.html", context)


def loginPage(request):

    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("main:index")
        else:
            messages.info(request, "Username or password is wrong")

    context = {}
    return render(request, "main/login.html", context)


def logoutUser(request):
    logout(request)
    return redirect("main:login")

atlo/main/views/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from django.db import transaction

from django.contrib.auth.models import User
from django.contrib.auth import login

from ..forms import TrafficForm, OtherParamForm, ImageForm, CreateUserForm
from ..models import Traffic, Results, OtherParam, Profile
from .. import logic


def index(request):
    if request.user.id is not None:
        user = request.user
        traffic = Traffic.objects.filter(user=user).last()
        print(traffic)
        if traffic is None:
            create_guest_account(request)
            return redirect("main:index")
    else:
        create_guest_account(request)
        return redirect("main:index")

    return redirect(reverse("main:activate_traffic", args=[traffic.pk]))


def create_guest_account(request):
    """If Guest account doesn't exist - create instance of User class with standart traffic and standart image and login it account"""

    try:
        user = User.objects.get(id=1)
        login(request, user)
    except User.DoesNotExist:
        user = User.objects.create_user(
            id=1, username="Guest", email="guest@gmail.com", password="1111"
        )
        user.save()

        traffic = Traffic(
            user=user, from_top=1, from_bottom=1, from_left=1, from_right=1
        )
        traffic.save()

        profile = Profile(user_id=user.id, image="default-user-icon-21.jpg")
        profile.save()
        login(request, user)


def addNewTraffic(request):
    user = request.user
    form_traffic = TrafficForm()
    if request.method == "POST":
        form_traffic = TrafficForm(request.POST)
        if form_traffic.is_valid():
            traffic = form_traffic.save(commit=False)
            traffic.user_id = user.id
            traffic.save()
            return redirect("main:index")
        else:
            messages.info(request, "Username or password is wrong")

    context = {"form_traffic": form_traffic}
    return render(request, "main/new_traffic.html", context)


@transaction.atomic
def editAccount(request, pk):
    user = request.user
    profile = Profile.objects.get(user_id=pk)

    new_image = {"image": request.POST.get("image")}
    new_user_data = {
        "username": request.POST.get("username"),
        "email": request.POST.get("email"),
    }
    same_value = (
        (profile.image == new_image["image"])
        and (user.username == new_user_data["username"])
        and (user.email == new_user_data["email"])
    )
    form = CreateUserForm()
    image_form = ImageForm(instance=profile)
    if not same_value:
        if request.method == "POST":
            image_form = ImageForm(request.POST, request.FILES, instance=profile)
            if image_form.is_valid():
                profile.save()
                return redirect("main:index")
    context = {"image_form": image_form}
    return render(request, "main/account.html", context)


def deleteTraffic(request, pk):
    traffic = Traffic.objects.get(id=pk)
    if request.method == "POST":
        traffic.delete()
        return redirect("main:index")
    context = {"item": traffic}
    return render(request, "main/delete_traffic.html", context)


def activate_traffic(request, pk):
    traffic = Traffic.objects.get(id=pk)
    user = request.user
    traffics = Traffic.objects.filter(user=user).all()

    new_traffic = {
        "from_left": request.POST.get("from_left"),
        "from_right": request.POST.get("from_right"),
        "from_top": request.POST.get("from_top"),
        "from_bottom": request.POST.get("from_bottom"),
    }

    empty_new_traffic = (
        new_traffic["from_bottom"] is None
        or new_traffic["from_left"] is None
        or new_traffic["from_right"] is None
        or new_traffic["from_top"] is None
    )
    if not empty_new_traffic:
        same_value = (
            traffic.from_bottom == int(new_traffic["from_bottom"])
            and traffic.from_left == int(new_traffic["from_left"])
            and traffic.from_right == int(new_traffic["from_right"])
            and traffic.from_top == int(new_traffic["from_top"])
        )
    else:
        same_value = False

    if not same_value:
        if request.method == "POST":
            form_traffic = TrafficForm(request.POST)
            traffic.from_bottom = int(new_traffic["from_bottom"])
            traffic.from_left = int(new_traffic["from_left"])
            traffic.from_right = int(new_traffic["from_right"])
            traffic.from_top = int(new_traffic["from_top"])
            if form_traffic.is_valid():
                traffic.save()

    other_param = OtherParam()
    other_param_form = OtherParamForm(request.POST or None)
    speed_checkbox_chacked = False
    iterations_checkbox_chacked = False

    if request.method == "POST":
        if other_param_form.is_valid():
            if "use_speed" in request.POST and "use_iterations" in request.POST:
                speed_checkbox_chacked = True
                iterations_checkbox_chacked = True
            elif "use_speed" in request.POST:
                speed_checkbox_chacked = True
            elif "use_iterations" in request.POST:
                iterations_checkbox_chacked = True

            other_param, created_other_param = OtherParam.objects.update_or_create(
                traffic=traffic,
                defaults={
                    "speed": speed_checkbox_chacked
                    and request.POST["speed"]
                    or other_param.speed,
                    "iterations": iterations_checkbox_chacked
                    and request.POST["iterations"]
                    or other_param.iterations,
                },
            )

    time_l_r, time_t_b = logic.get_green_signals_time(traffic)

    collapses = logic.get_collapses(traffic, other_param)

    results, created = Results.objects.update_or_create(
        traffic=traffic,
        defaults={
            "time_lf_rt": time_l_r,
            "time_tp_bm": time_t_b,
            "top_collapse": collapses["top_collapse"],
            "bottom_collapse": collapses["bottom_collapse"],
            "left_collapse": collapses["left_collapse"],
            "right_collapse": collapses["right_collapse"],
        },
    )

    context = {
        "speed_checkbox_chacked": speed_checkbox_chacked,
        "iterations_checkbox_chacked": iterations_checkbox_chacked,
        "other_param": other_param,
        "traffic": traffic,
        "traffics": traffics,
        "time_lf_rt": time_l_r,
        "time_tp_bm": time_t_b,
        "collapses": collapses,
    }
    return render(request, "main/index.html", context)

atlo/main/templates/main/account.html
{% extends 'main/main.html' %}
{% load static %}

{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900">
        <div
            class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div
                class="w-full bg-slate-400 rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1
                        class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Change an account
                    </h1>
                    <form
                        class="space-y-2 md:space-y-4"
                        method="POST"
                        action=""
                        anctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="flex justify-center break-after-column">
                            <div class="mb-3 w-96">
                                <label for="formFile" class="form-label inline-block mb-2 text-gray-700">Your avatar is:
                                    <img
                                        class="w-10 inline-block h-10 text-white text-sm"
                                        src="{{ user.profile.image.url }}"
                                        alt="avatar"
                                        }}="}}"></label>
                                <label class="form-label block mb-2 text-gray-700">"{{user.profile.image.url}}"</label>
                                {{ image_form.image }}
                            </div>
                        </div>
                        <button
                            type="submit"
                            class="w-full py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Change an account</button>

                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            Change your mind?
                            <a
                                href="{% url 'main:index' %}"
                                class="font-medium text-primary-600 hover:underline dark:text-primary-500">Back to main page</a>
                        </p>

                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

atlo/main/templates/main/index.html
{% extends 'main/main.html' %}
{% load static %}
{% block content %}

    <form
        class="grid grid-cols-3 auto-rows-[250px] text-orange-700 bg-slate-400 "
        method="post"
        action="">
        {% csrf_token %}
        <div class="border-r-4 border-b-4 border-white rounded-br-3xl bg-lime-600">
            <p class="m-2 inline-block text-white decoration-solid text-xl ">Hello
                {{ user.username }}</p>
            <a href="{% url 'main:account_page' user.id %}"><img
                class="w-10 inline-block h-10 rounded text-white text-sm"
                src="{{ user.profile.image.url }}"
                alt="avatar"></a>
            <p class="m-2 text-white text-l">Curent experiment ID is
                {{ traffic.id }}</p>
            <p>
                <a href="{% url 'main:login'%}" class="m-2 text-indigo-600">Logout</a>
            </p>
        </div>
        <div class="relative bg-slate-400 flex items-center justify-center">
            {% if collapses.top_collapse %}
                <div
                    class="absolute top-0 mb-4 rounded-lg bg-danger-100 py-5 px-6 text-base text-danger-700"
                    role="alert">
                    There were
                    {{ collapses.top_collapse }}
                    collapses in
                    {{ other_param.iterations }}
                    iterations
                </div>
            {% endif %}
            <p>
                <b>Number of traffic</b><br>
                <input
                    type="text"
                    name="from_top"
                    inputmode="numeric"
                    required="required"
                    size="15"
                    value="{{ traffic.from_top }}">
            </p>
        </div>
        <div
            class="relative overflow-x-auto shadow-md bg-lime-600 border-l-4 border-b-4 border-white rounded-bl-3xl">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead
                    class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th>Action</th>
                        <th>ID</th>
                        <th>From left</th>
                        <th>From top</th>
                        <th>From right</th>
                        <th>From bottom</th>
                        <th>Del</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in traffics %}
                        <tr
                            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                            <td class="px-2 py-2">
                                <a
                                    class="bg-sky-500 text-white active:bg-sky-600 text-xs px-1 py-1 rounded-full shadow hover:shadow-md outline-none focus:outline-none ease-linear transition-all duration-150"
                                    href="{% url 'main:activate_traffic' i.id %}">Activate</a>
                            </td>
                            <td class="px-2 py-2">{{ i.id }}</td>
                            <td class="px-2 py-2">{{ i.from_left }}</td>
                            <td class="px-2 py-2">{{ i.from_top }}</td>
                            <td class="px-2 py-2">{{ i.from_right }}</td>
                            <td class="px-2 py-2">{{ i.from_bottom }}</td>
                            <td class="px-2 py-2">
                                <a
                                    class="bg-red-500 text-white active:bg-red-600 text-xs px-2 py-1 rounded-full shadow hover:shadow-md outline-none focus:outline-none ease-linear transition-all duration-150"
                                    href="{% url 'main:delete_traffic' i.id %}">X</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="flex">
                <a
                    href="{% url 'main:add_new_traffic' %}"
                    class="w-full px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add new experiment</a>

            </div>
        </div>

        <div class="relative bg-slate-400 flex items-center justify-center">
            {% if collapses.left_collapse %}
                <div
                    class="absolute top-0 mb-4 rounded-lg bg-danger-100 py-5 px-6 text-base text-danger-700"
                    role="alert">
                    There were
                    {{ collapses.left_collapse }}
                    collapses in
                    {{ other_param.iterations }}
                    iterations
                </div>
            {% endif %}
            <p>
                <b>Number of traffic</b><br>
                <input
                    type="text"
                    name="from_left"
                    inputmode="numeric"
                    required="required"
                    size="15"
                    value="{{ traffic.from_left }}"/>
            </p>
        </div>
        <div class="bg-slate-400 flex items-center justify-center grid grid-cols-2">
            <div
                class="text-xl m-auto font-bold rounded-full bg-slate-400 flex items-center justify-center h-20 w-20
                {% if time_tp_bm > time_lf_rt %}
                text-green-700 border-8 border-green-700
                {% else %}
                text-red-700 border-8 border-red-700
                {% endif %}
                ">
                &#129091;
                {{ time_tp_bm }}
            </div>
            <div
                class="text-xl m-auto font-bold rounded-full bg-slate-400 flex items-center justify-center h-20 w-20
                {% if time_tp_bm < time_lf_rt %}
                text-green-700 border-8 border-green-700
                {% else %}
                text-red-700 border-8 border-red-700
                {% endif %}
                ">
                &#129088;
                {{ time_lf_rt }}
            </div>
            <div
                class="text-xl m-auto font-bold rounded-full bg-slate-400 flex items-center justify-center h-20 w-20
                {% if time_tp_bm < time_lf_rt %}
                text-green-700 border-8 border-green-700
                {% else %}
                text-red-700 border-8 border-red-700
                {% endif %}
                ">
                &#129090;
                {{ time_lf_rt }}</div>
            <div
                class="text-xl m-auto font-bold rounded-full bg-slate-400 flex items-center justify-center h-20 w-20
                {% if time_tp_bm > time_lf_rt %}
                text-green-700 border-8 border-green-700
                {% else %}
                text-red-700 border-8 border-red-700
                {% endif %}
                ">
                &#129089;
                {{ time_tp_bm }}</div>
        </div>
        <div class="relative bg-slate-400 flex items-center justify-center">
            {% if collapses.right_collapse %}
                <div
                    class="absolute top-0 mb-4 rounded-lg bg-danger-100 py-5 px-6 text-base text-danger-700"
                    role="alert">
                    There were
                    {{ collapses.right_collapse }}
                    collapses in
                    {{ other_param.iterations }}
                    iterations
                </div>
            {% endif %}
            <p>
                <b>Number of traffic</b><br>
                <input
                    type="text"
                    formmethod="post"
                    name="from_right"
                    inputmode="numeric"
                    required="required"
                    size="15"
                    value="{{ traffic.from_right }}">
            </p>
        </div>

        <div class="bg-lime-600 border-r-4 border-t-4 border-white rounded-tr-3xl">
            <p class="m-2 text-white text-xl">Other parameters</p>
            <div>
                <input
                    class="m-2"
                    type="checkbox"
                    name="use_speed"
                    {% if speed_checkbox_chacked %}
                    checked="checked"
                    {% endif %}/>
                <label class="m-2 text-white text-l" for="speed">Speed</label>
                <input
                    type="text"
                    formmethod="post"
                    name="speed"
                    inputmode="numeric"
                    required="required"
                    size="15"
                    value="{{ other_param.speed }}"/>
            </div>
            <div>
                <input
                    class="m-2"
                    type="checkbox"
                    name="use_iterations"
                    {% if iterations_checkbox_chacked %}
                    checked="checked"
                    {% endif %}/>
                <label class="m-2 text-white text-l" for="iterations">Iterations</label>
                <input
                    type="text"
                    formmethod="post"
                    name="iterations"
                    inputmode="numeric"
                    required="required"
                    size="15"
                    value="{{ other_param.iterations }}"/>
            </div>

        </div>
        <div class="relative bg-slate-400 flex items-center justify-center">
            {% if collapses.bottom_collapse %}
                <div
                    class="absolute top-0 mb-4 rounded-lg bg-danger-100 py-5 px-6 text-base text-danger-700"
                    role="alert">
                    There were
                    {{ collapses.bottom_collapse }}
                    collapses in
                    {{ other_param.iterations }}
                    iterations
                </div>
            {% endif %}
            <p>
                <b>Number of traffic</b><br>
                <input
                    type="text"
                    name="from_bottom"
                    inputmode="numeric"
                    required="required"
                    size="15"
                    value="{{ traffic.from_bottom }}">
            </p>
        </div>
        <div class="p-2 bg-lime-600 border-l-4 border-t-4 border-white rounded-tl-3xl">
            <input
                class="w-full px-3 py-2 text-xs font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                type="submit"
                value='Calculate'
                name='calculate'/>
        </div>
    </form>
{% endblock %}

atlo/main/templates/main/login.html
{% extends 'main/main.html' %}

{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900">
        <div
            class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div
                class="w-full bg-slate-400 rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1
                        class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Sign in to your account
                    </h1>
                    <form class="space-y-4 md:space-y-6" method="POST" action="">
                        {% csrf_token %}
                        <div>
                            <label
                                for="username"
                                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your name</label>
                            <input
                                type="text"
                                name="username"
                                id="username"
                                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                placeholder="Your name"
                                required="">
                        </div>
                        <div>
                            <label
                                for="password"
                                class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                            <input
                                type="password"
                                name="password"
                                id="password"
                                placeholder="••••••••"
                                class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                required="">
                        </div>
                        {% for message in messages %}
                            <p class="bg-green-300">{{ message }}</p>
                        {% endfor %}
                        <button
                            type="submit"
                            class="w-full py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Sign in</button>
                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            Don’t have an account yet?
                            <a
                                href="{% url 'main:register' %}"
                                class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}